services:
  postgres:
    image: postgres:18
    container_name: incidentiq-postgres

    environment:
      POSTGRES_DB: incidentiq
      POSTGRES_USER: incidentiq
      POSTGRES_PASSWORD: incidentiq_dev

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: